apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      namespace: nestjs-kubernetes-namespace
      name: registry-secret
    stringData:
      .dockerconfigjson: |
        {"auths":{"registry.gitlab.com":{"auth":"AUTH_SECRET_KEY"}}}
    type: kubernetes.io/dockerconfigjson
  - apiVersion: v1
    kind: Secret
    metadata:
      namespace: nestjs-kubernetes-namespace
      name: nestjs-kubernetes-secret
    stringData:
      POSTGRES_PASSWORD: "POSTGRES_PASSWORD"
      POSTGRES_URL: "postgres://postgres:POSTGRES_PASSWORD@postgres-service:5432/nestjs"
    type: Opaque